name: eq_indexd_stack
description: "A high-performance lazy-loading IndexedStack for Flutter that initializes pages only when needed."
version: 0.0.4
homepage: https://github.com/eq-devs/eq.indexd.stack
repository: https://github.com/eq-devs/eq.indexd.stack
issue_tracker: https://github.com/eq-devs/eq.indexd.stack/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: